// In welk deel van de winkel ligt een ingrediënt?
//
// De boodschappenlijst stond alfabetisch, waardoor je voor een recept drie keer
// door de winkel loopt. Gegroepeerd per schap loop je één ronde.
//
// Dit werkt op regels en niet op een tabel met alle 1900 ingrediëntnamen: een
// nieuw recept met "Rode Paprika" valt dan meteen goed, zonder dat er iets
// bijgewerkt hoeft te worden. De regels worden op volgorde geprobeerd, dus de
// specifieke staan boven de algemene.

export const AISLES = [
    { id: 'groente', naam: 'Groente & fruit', icoon: 'fa-solid fa-carrot' },
    { id: 'vlees', naam: 'Vlees & vis', icoon: 'fa-solid fa-drumstick-bite' },
    { id: 'zuivel', naam: 'Zuivel & eieren', icoon: 'fa-solid fa-cheese' },
    { id: 'brood', naam: 'Brood & beleg', icoon: 'fa-solid fa-bread-slice' },
    { id: 'voorraad', naam: 'Voorraad', icoon: 'fa-solid fa-box-open' },
    { id: 'kruiden', naam: 'Kruiden & specerijen', icoon: 'fa-solid fa-mortar-pestle' },
    { id: 'bakken', naam: 'Bakken & zoet', icoon: 'fa-solid fa-cookie' },
    { id: 'diepvries', naam: 'Diepvries', icoon: 'fa-solid fa-snowflake' },
    { id: 'drank', naam: 'Drank', icoon: 'fa-solid fa-wine-bottle' },
    { id: 'overig', naam: 'Overig', icoon: 'fa-solid fa-basket-shopping' },
];

// De regels, van specifiek naar algemeen. Elk woord wordt op hele woorden
// vergeleken, dus "ham" vindt niet "graham".
const RULES = [
    // Azijn staat voor drank, anders belandt "Red Wine Vinegar" bij de wijn.
    ['voorraad', ['vinegar', 'water chestnut', 'water chestnuts', 'rice wine vinegar']],
    // Water koop je niet; dat zetten we onderaan de lijst en niet bij de drank.
    ['overig', ['water']],
    // Paprika's en verse chilipepers staan voor de specerijen: "Red Pepper" is een
    // paprika, terwijl "Pepper" zonder meer om zwarte peper gaat.
    ['groente', ['bell pepper', 'bell peppers', 'red pepper', 'green pepper', 'yellow pepper',
                 'orange pepper', 'sweet pepper', 'sweet peppers', 'mixed peppers', 'romano pepper',
                 'roasted pepper', 'roasted peppers', 'padron peppers', 'peppadew peppers',
                 'banana pepper', 'habanero pepper', 'jalapeño peppers', 'jalapeno peppers',
                 'scotch bonnet', 'chile peppers', 'chili peppers', 'chilli pepper', 'chile pepper',
                 'pickled red peppers']],
    // Verder eerst de gevallen die een latere, algemenere regel verkeerd zou pakken.
    ['diepvries', ['frozen', 'ice cream', 'ice cubes', 'sorbet', 'frozen peas', 'puff pastry',
                   'filo pastry', 'shortcrust pastry', 'pastry sheets', 'ice']],
    ['kruiden', ['salt', 'pepper', 'peppercorns', 'paprika', 'cumin', 'coriander seeds', 'turmeric',
                 'cinnamon', 'nutmeg', 'cloves', 'cardamom', 'allspice', 'oregano', 'thyme leaves',
                 'bay leaf', 'bay leaves', 'chilli powder', 'chili powder', 'chilli flakes',
                 'curry powder', 'garam masala', 'saffron', 'star anise', 'fennel seeds',
                 'mustard seeds', 'sesame seed', 'poppy seeds', 'caraway', 'juniper', 'sumac',
                 'zaatar', 'ras el hanout', 'five spice', 'cayenne', 'ginger powder', 'msg',
                 'stock cube', 'bouillon', 'vanilla extract', 'vanilla', 'food colouring',
                 'food coloring', 'seasoning', 'spice', 'spices', 'herbs',
                 'ground ginger', 'ground coriander', 'ground cumin', 'ground cinnamon',
                 'ground cardamom', 'ground clove', 'ground cloves', 'ground nutmeg',
                 'ground turmeric', 'ground allspice', 'ground white pepper', 'ground black pepper',
                 'chilli seasoning', 'curry leaves']],
    ['bakken', ['baking powder', 'bicarbonate of soda', 'baking soda', 'cream of tartar', 'yeast',
                'gelatine', 'gelatin', 'agar', 'vanilla', 'vanilla extract', 'almond extract',
                'flour', 'sugar', 'icing sugar', 'caster sugar', 'brown sugar', 'muscovado',
                'demerara', 'chocolate', 'cocoa powder', 'cacao', 'chocolate chips', 'marzipan',
                'marshmallow', 'marshmallows', 'sprinkles', 'honey', 'golden syrup', 'maple syrup',
                'treacle', 'molasses', 'condensed milk', 'evaporated milk', 'custard powder',
                'digestive biscuits', 'oats', 'desiccated coconut', 'jam', 'nutella',
                'almonds', 'walnuts', 'pecan nuts', 'hazelnuts', 'pistachios', 'cashew nuts',
                'peanuts', 'nuts', 'raisins', 'sultanas', 'dates', 'dried apricots', 'currants',
                'cranberries', 'mixed peel', 'glace cherries']],
    ['vlees', ['beef', 'steak', 'veal', 'lamb', 'mutton', 'pork', 'bacon', 'gammon', 'ham',
               'sausage', 'sausages', 'chorizo', 'pancetta', 'prosciutto', 'salami', 'pepperoni',
               'chicken', 'turkey', 'duck', 'quail', 'pigeon', 'goat', 'mince', 'minced beef',
               'minced pork', 'brisket', 'oxtail', 'ribs', 'shank', 'tripe', 'liver', 'kidney',
               'salmon', 'tuna', 'cod', 'haddock', 'pollock', 'trout', 'mackerel', 'sardines',
               'sea bass', 'seabass', 'monkfish', 'halibut', 'snapper', 'tilapia', 'herring',
               'prawns', 'shrimp', 'crab', 'lobster', 'squid', 'calamari', 'octopus', 'mussels',
               'clams', 'oysters', 'scallops', 'anchovies', 'anchovy', 'fish', 'seafood',
               'fishballs', 'catfish', 'milkfish', 'codfish', 'tofu', 'tempeh']],
    ['zuivel', ['milk', 'buttermilk', 'butter', 'margarine', 'cream', 'creme fraiche',
                'crème fraîche', 'sour cream', 'yoghurt', 'yogurt', 'cheese', 'mozzarella',
                'parmesan', 'parmigiano', 'parmigiano-reggiano', 'reggiano', 'grana padano',
                'cheddar', 'feta', 'ricotta', 'mascarpone', 'halloumi', 'paneer',
                'gruyere', 'gouda', 'brie', 'stilton', 'pecorino', 'emmental', 'quark',
                'cottage cheese', 'cream cheese', 'egg', 'eggs', 'egg yolks', 'egg white',
                'egg whites', 'ghee', 'lard', 'suet']],
    ['brood', ['bread', 'breadcrumbs', 'panko', 'baguette', 'ciabatta', 'brioche', 'pita',
               'pitta', 'naan', 'tortilla', 'tortillas', 'wraps', 'roti', 'chapati', 'bagel',
               'buns', 'bun', 'rolls', 'croissant', 'crumpets', 'muffins', 'crackers',
               'wonton wrappers', 'rice paper', 'lasagne sheets', 'pastry']],
    ['groente', ['onion', 'onions', 'shallots', 'garlic', 'leek', 'celery', 'carrots', 'carrot',
                 'potatoes', 'potato', 'sweet potatoes', 'tomato', 'tomatoes', 'cherry tomatoes',
                 'cucumber', 'lettuce', 'rocket', 'spinach', 'kale', 'cabbage', 'broccoli',
                 'cauliflower', 'courgettes', 'aubergine', 'eggplant', 'eggplants', 'daikon',
                 'bamboo shoot', 'bamboo shoots', 'bok choy', 'pak choi', 'mangetout',
                 'sugar snap peas', 'edamame', 'chicory', 'endive', 'samphire', 'kohlrabi', 'pepper', 'peppers', 'red pepper',
                 'green pepper', 'yellow pepper', 'chilli', 'chillies', 'chile', 'mushrooms',
                 'mushroom', 'peas', 'green beans', 'beansprouts', 'asparagus', 'artichoke',
                 'beetroot', 'radish', 'turnips', 'parsnips', 'squash', 'pumpkin', 'corn',
                 'sweetcorn', 'avocado', 'ginger', 'lemongrass', 'spring onions', 'fennel',
                 'celeriac', 'okra', 'plantain', 'yam', 'cassava', 'lime', 'lemon', 'orange',
                 'grapefruit', 'apple', 'apples', 'pear', 'banana', 'mango', 'pineapple',
                 'peaches', 'strawberries', 'raspberries', 'blueberries', 'blackberries',
                 'cherries', 'grapes', 'melon', 'watermelon', 'kiwi', 'papaya', 'passion fruit',
                 'rhubarb', 'coriander', 'parsley', 'basil', 'mint', 'dill', 'chives', 'rosemary',
                 'sage', 'tarragon', 'thyme', 'curry leaves', 'kaffir lime leaves', 'sorrel',
                 'watercress', 'salad', 'herb']],
    ['drank', ['wine', 'red wine', 'white wine', 'beer', 'lager', 'stout', 'cider', 'rum',
               'whisky', 'whiskey', 'vodka', 'gin', 'brandy', 'cognac', 'tequila', 'sherry',
               'vermouth', 'liqueur', 'schnapps', 'bourbon', 'sake', 'mirin', 'prosecco',
               'champagne', 'cola', 'lemonade', 'soda water', 'tonic', 'ginger ale',
               'orange juice', 'apple juice', 'cranberry juice', 'pineapple juice', 'coffee',
               'espresso', 'tea', 'water', 'bitters', 'curacao', 'triple sec', 'amaretto',
               'grenadine', 'kahlua', 'campari', 'cointreau', 'sambuca', 'galliano', 'benedictine',
               'chartreuse', 'absinthe', 'ouzo', 'grappa', 'pastis', 'aperol', 'pisco', 'cachaca',
               'mezcal', 'creme de', 'schnaps', 'soda', 'cola', 'sprite', 'fanta', 'tonic water',
               'club soda', 'root beer', 'squash', 'cordial', 'syrup', 'juice', 'ale', 'porter',
               'mead', 'wine', 'port', 'madeira', 'marsala', 'liquor', 'spirit', 'proof rum',
               'dry vermouth', 'sweet vermouth']],
    ['voorraad', ['pasta', 'spaghetti', 'penne', 'macaroni', 'fettuccine', 'tagliatelle',
                  'linguine', 'rigatoni', 'fusilli', 'farfalle', 'noodles', 'noodle', 'udon',
                  'ramen', 'soba', 'vermicelli', 'rice', 'risotto rice', 'couscous', 'quinoa',
                  'bulgur', 'polenta', 'lentils', 'chickpeas', 'beans', 'kidney beans',
                  'black beans', 'cannellini beans', 'butter beans', 'stock', 'broth', 'passata',
                  'tomato puree', 'chopped tomatoes', 'coconut milk', 'coconut cream', 'olive oil',
                  'vegetable oil', 'sunflower oil', 'sesame seed oil', 'peanut oil', 'rapeseed oil',
                  'oil', 'vinegar', 'soy sauce', 'fish sauce', 'oyster sauce', 'hoisin',
                  'worcestershire sauce', 'tabasco', 'sriracha', 'ketchup', 'mayonnaise',
                  'mustard', 'horseradish', 'tahini', 'peanut butter', 'miso', 'curry paste',
                  'harissa', 'pesto', 'chutney', 'pickles', 'capers', 'olives', 'gherkins',
                  'sun-dried tomatoes', 'cornstarch', 'corn flour', 'semolina', 'gram flour',
                  'tapioca', 'sesame', 'seeds']],
];

// Uitzonderingen waar de regels de mist in gaan.
const OVERRIDES = {
    'coconut milk': 'voorraad',
    'almond milk': 'voorraad',
    'soya milk': 'voorraad',
    'oat milk': 'voorraad',
    'milk chocolate': 'bakken',
    'chocolate milk': 'drank',
    'white chocolate': 'bakken',
    'dark chocolate': 'bakken',
    'coconut cream': 'voorraad',
    'peanut butter': 'voorraad',
    'cocoa butter': 'bakken',
    'butter beans': 'voorraad',
    'buttermilk': 'zuivel',
    'butternut squash': 'groente',
    'beef tomato': 'groente',
    'beef tomatoes': 'groente',
    'goat cheese': 'zuivel',
    'goats cheese': 'zuivel',
    "goat's cheese": 'zuivel',
    'chicken stock': 'voorraad',
    'beef stock': 'voorraad',
    'vegetable stock': 'voorraad',
    'fish stock': 'voorraad',
    'egg noodles': 'voorraad',
    'lemon juice': 'groente',
    'lime juice': 'groente',
    'tomato ketchup': 'voorraad',
    'sesame seed': 'kruiden',
    'sesame seed oil': 'voorraad',
    'vanilla ice cream': 'diepvries',
    'ice cream': 'diepvries',
    'salted butter': 'zuivel',
    'unsalted butter': 'zuivel',
    'garlic powder': 'kruiden',
    'onion powder': 'kruiden',
    'onion salt': 'kruiden',
    'celery salt': 'kruiden',
    'ginger paste': 'kruiden',
    'garlic paste': 'kruiden',
    'ginger garlic paste': 'kruiden',
    'crushed ice': 'diepvries',
    'prawn crackers': 'voorraad',
    'fish sauce': 'voorraad',
    'oyster sauce': 'voorraad',
    'anchovy paste': 'voorraad',
    'chicken bouillon': 'kruiden',
    'coconut water': 'drank',
    'rose water': 'bakken',
    'orange blossom water': 'bakken',
    'bread flour': 'bakken',
    'plain flour': 'bakken',
    'rice flour': 'bakken',
    'corn flour': 'bakken',
    'gram flour': 'bakken',
    'coconut flour': 'bakken',
    'potato starch': 'voorraad',
    'sweet potatoes': 'groente',
    'tomato puree': 'voorraad',
    'sundried tomatoes': 'voorraad',
    'sun-dried tomatoes': 'voorraad',
    'scotch bonnet': 'groente',
    'scotch': 'drank',
    'jalapeno': 'groente',
    'jalapeño': 'groente',
    'challots': 'groente',
    'marjoram': 'groente',
    'coconut': 'bakken',
    'pistachio': 'bakken',
    'shortening': 'bakken',
    'dulce de leche': 'bakken',
    'almond extract': 'kruiden',
    'peppermint extract': 'kruiden',
    'ground clove': 'kruiden',
    'tamarind paste': 'voorraad',
    'ground crayfish': 'voorraad',
    'hotsauce': 'voorraad',
    'hot sauce': 'voorraad',
    'maraschino cherry': 'voorraad',
    'maraschino cherries': 'voorraad',
    'sweet and sour': 'voorraad',
    'sour mix': 'voorraad',
    'squash': 'groente',
    'butternut squash': 'groente',
    'tonic water': 'drank',
    'soda water': 'drank',
    'sparkling water': 'drank',
    'mineral water': 'drank',
    'coconut water': 'drank',
    'kewra water': 'bakken',
    'chopped tomatoes': 'voorraad',
    'tinned tomatoes': 'voorraad',
    'tinned tomatos': 'voorraad',
    'canned tomatoes': 'voorraad',
    'passata': 'voorraad',
    'black eyed peas': 'voorraad',
    'split peas': 'voorraad',
    'dried peas': 'voorraad',
    'mushy peas': 'voorraad',
    'frozen peas': 'diepvries',
    'petit pois': 'diepvries',
    'stir-fry vegetables': 'groente',
    'mixed vegetables': 'diepvries',
    'dried apricots': 'bakken',
    'dried fruit': 'bakken',
    'apricot jam': 'bakken',
    'olive oil': 'voorraad',
    'extra virgin olive oil': 'voorraad',
    'sunflower oil': 'voorraad',
    'vegetable oil': 'voorraad',
    'baking powder': 'bakken',
    'vanilla extract': 'bakken',
    'ground ginger': 'kruiden',
    'ginger': 'groente',
    'garlic': 'groente',
    'lemongrass': 'groente',
    'galangal': 'groente',
    'pak choi': 'groente',
    'sauerkraut': 'voorraad',
    'cornmeal': 'bakken',
    'polenta': 'voorraad',
    'custard': 'zuivel',
    'starch': 'voorraad',
    'prunes': 'bakken',
    'figs': 'groente',
    'swede': 'groente',
    'breadfruit': 'groente',
    'callaloo': 'groente',
    'toor dal': 'voorraad',
    'soya bean': 'voorraad',
    'pretzels': 'voorraad',
    'cashews': 'bakken',
    'pecans': 'bakken',
    'roasted peanut': 'bakken',
    'coconut flakes': 'bakken',
    'meringue nests': 'bakken',
    'hummus': 'voorraad',
    'chimichurri sauce': 'voorraad',
    'barbeque sauce': 'voorraad',
    'barbecue sauce': 'voorraad',
    'black pudding': 'vlees',
    'bagoong alamang': 'voorraad',
    'pul biber': 'kruiden',
    'ground cardomom': 'kruiden',
    'almond essence': 'bakken',
    'red pepper paste': 'voorraad',
    'red pepper sauce': 'voorraad',
    'red pepper flakes': 'kruiden',
    'red pepper powder': 'kruiden',
    'lemon pepper': 'kruiden',
    'ground cameroon pepper': 'kruiden',
    'ground fresh red chile pepper': 'kruiden',
    'puréed chile pepper': 'voorraad',
    'dried cayenne pepper seeds': 'kruiden',
    'dry ground cayenne pepper': 'kruiden',
    'dr. pepper': 'drank',
    'peppermint extract': 'bakken',
    'dashi': 'voorraad',
    'urad dal': 'voorraad',
    'asafoetida powder': 'kruiden',
    'rosewater': 'bakken',
    'gula jawa': 'bakken',
    'mincemeat': 'bakken',
    'fruit mix': 'bakken',
    'vegetable millk': 'voorraad',
};

const WORD_CACHE = new Map();

function matches(name, word) {
    let pattern = WORD_CACHE.get(word);
    if (!pattern) {
        const escaped = word.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        pattern = new RegExp(`(^|\\s)${escaped}(s|es)?($|\\s)`);
        WORD_CACHE.set(word, pattern);
    }
    return pattern.test(name);
}

/**
 * Geeft het schap waar dit ingrediënt ligt.
 *
 * `fallback` is waar onbekende namen terechtkomen. Bij de cocktails is dat
 * 'drank': er zijn honderden likeuren en die zijn nooit allemaal op te sommen,
 * maar een onbekend ingrediënt in een cocktail staat vrijwel altijd bij de drank.
 */
export function aisleOf(ingredientName, fallback = 'overig') {
    const name = (ingredientName || '').toLowerCase().trim();
    if (!name) return fallback;
    if (OVERRIDES[name]) return OVERRIDES[name];

    for (const [aisle, words] of RULES) {
        if (words.some((word) => matches(name, word))) return aisle;
    }
    return fallback;
}

export function aisleInfo(id) {
    return AISLES.find((aisle) => aisle.id === id) || AISLES[AISLES.length - 1];
}
